//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dektopCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class desktopDBEntities1 : DbContext
    {
        public desktopDBEntities1()
            : base("name=desktopDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analytic> Analytic { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CSobject> CSobject { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<MPS> MPS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
