//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dektopCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergType
    {
        public int ID { get; set; }
        public int EmergID { get; set; }
        public string EmergTypeName { get; set; }
    
        public virtual Emerg Emerg { get; set; }
    }
}
