//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dektopCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int ID { get; set; }
        public string MarkName { get; set; }
        public string MakrImage { get; set; }
    }
}
